### ISSUE TITLE
fix(db): resolve #3176 migration typecheck errors and ratchet baseline down

### ISSUE THREAD

**Issue by kaeawc** [kaeawc/auto-mobile#3204]
## Summary

The scoped typecheck gate baseline (`scripts/typecheck-baseline.txt`, from #3001/#3187, commit d12887d4) is **missing 6 pre-existing errors** introduced by #3176 (206460d2, "extract telemetry event tables"). #3187 generated its baseline from a base predating #3176's migration files and merged after it, so the errors were never captured. This is textbook base drift (see the header comment in `scripts/typecheck-baseline.sh`): **every PR rebased past #3176 fails the typecheck gate** on errors it did not introduce.

PR #3197 worked around this by recording the 6 signatures in the baseline (commit on that branch) so unrelated PRs stop failing. This issue tracks the real fix.

## The 6 errors (reproduced with the pinned tsc 6.0.3)

```
src/db/migrations/2026_07_02_000_event_composite_indexes.ts: error TS2345: Argument of type 'string' is not assignable to parameter of type 'ReferenceExpression<unknown, never>'.  (x2)
src/db/migrations/2026_07_02_000_event_composite_indexes.ts: error TS2769: No overload matches this call.
src/db/migrations/2026_07_03_000_drop_redundant_device_indexes.ts: error TS2345: Argument of type 'string' is not assignable to parameter of type 'ReferenceExpression<unknown, never>'.  (x2)
src/db/migrations/2026_07_03_000_drop_redundant_device_indexes.ts: error TS2769: No overload matches this call.
```

These are kysely query-builder typing errors — raw `string` column/index references passed where kysely expects a typed `ReferenceExpression`. Likely the migration uses `sql`/`.createIndex(...).columns([...])` or `.on(...)` with untyped strings against a generic `Kysely<unknown>` schema.

## Proposed direction

Fix the typing in the two migration files (e.g. type the migration `Kysely<...>` schema, use `sql.ref(...)`/`sql.raw(...)`, or the typed column-reference API) so `bunx tsc --noEmit --ignoreDeprecations 6.0` reports zero errors for them. Then `bun run typecheck:update` and commit the shrunk baseline (removing the 6 signatures recorded in #3197).

## Acceptance
- [ ] `bunx tsc --noEmit` reports no errors in `src/db/migrations/2026_07_02_000_*` and `2026_07_03_000_*`.
- [ ] `scripts/typecheck-baseline.txt` regenerated (6 fewer errors); gate green.
- [ ] Migration behavior unchanged (existing migration/db tests stay green).

## Provenance

Surfaced while merging #3197 (consolidate ProcessExecutor/HostCommandExecutor exec seam, closes #2945): the rebase onto current main turned the gate red on these 6 unrelated errors.

**Comment by kaeawc** [comment]
Fixed directly in #3197 — the tableExists() helper in both migration files now uses the typed `sql` template instead of `selectFrom("sqlite_master" as never)`, removing the 6 tsc errors at the source. Baseline stays at 552 (no growth). Rather than record the errors, the root cause is resolved.
