### ISSUE TITLE
CI failures after #562: native addon build errors

### ISSUE THREAD

**Issue by kaeawc** [kaeawc/auto-mobile#568]
## Summary
After merging #562 (memory leak detection tooling), CI on `main` and PRs is failing due to native addon build issues for `memwatch-next` and `heapdump`.

## Current behavior
- **Memory Leak Detection** job fails during `bun pm trust memwatch-next heapdump`.
  - Example error (Node 20.19.6): `AddGCEpilogueCallback is not a member of v8::V8` and multiple `v8::Object::Set` signature errors.
  - Run: https://github.com/kaeawc/auto-mobile/actions/runs/20874624627/job/59982007081
- **Docker builds** fail because `bun install` tries to build `heapdump` without Python in the builder image.
  - Example error: `gyp ERR! find Python ... Could not find any Python installation to use`.
  - Runs: https://github.com/kaeawc/auto-mobile/actions/runs/20874624627/job/59982030730 and https://github.com/kaeawc/auto-mobile/actions/runs/20874624627/job/59982030733
- These failures impact **main** because the merge workflow publishes the Docker image using the same Dockerfile.

## Expected behavior
- Memory leak detection should run even if native addons are missing (or use a supported Node version).
- Docker builds should not fail due to dev-only native addons.

## Proposed fixes
- In the memory leak job:
  - Use Node 18 for native addon builds (or skip memwatch when it fails).
  - Treat `bun pm trust memwatch-next` / `heapdump` as non-fatal when already trusted or incompatible.
- In Docker builds:
  - Use `bun install --production` (skip dev deps), **or**
  - Install Python + build toolchain in the builder image.

## Related
- PR that introduced the failures: #562
