### ISSUE TITLE
PlanExecutor injects __lockNamespace on every step, but only criticalSection/barrier schemas accept it

### ISSUE THREAD

**Issue by RyeBread1026** [kaeawc/auto-mobile#4613]
## Summary

`0.0.45` broke `executePlan` for any plan that doesn't use `criticalSection`/`barrier` at all. Every step fails Zod validation with `unrecognized_keys: ["__lockNamespace"]` the moment a `sessionUuid` is present, even for a plain `tapOn`.

## Root cause

In `PlanExecutor.buildEnhancedStepParams` (`dist/src/index.js`), the lock-namespace injection isn't gated by tool type:

```js
if (Q && !W.sessionUuid) W.sessionUuid = Q, ...
if (Q && !W.__lockNamespace) W.__lockNamespace = Q;
return W
```

This runs for every step regardless of `$.tool`. The built params then get validated against that step's own tool schema via `X.schema.parse(Y)`. Per #3942 (which introduced this), `__lockNamespace` is intentionally declared "only by the `criticalSection`/`barrier` schemas" - every other tool schema (confirmed for `tapOn`) has no such field and is strict about unrecognized keys, so the step fails outright.

Confirmed `__lockNamespace` doesn't exist anywhere in `0.0.44` (`tool-definitions.json` / `index.js`) - this is a clean regression introduced by #3942 in `0.0.45`.

## Repro

Any JUnit `executePlan()` call against a plan with no `criticalSection`/`barrier` steps, once a `sessionUuid` is set on the execution context. First failure is whatever step follows plan setup - in our case step 6, a `tapOn`:

```
{
  "code": "unrecognized_keys",
  "keys": ["__lockNamespace"],
  "path": [],
  "message": "Unrecognized key: \"__lockNamespace\""
}
```

## Suggested fix

Gate the injection to the tools that actually declare the field, e.g.:

```js
if (Q && !W.__lockNamespace && (X.name === "criticalSection" || X.name === "barrier")) W.__lockNamespace = Q;
```

or check `X.schema`'s shape for the key before assigning, so it stays correct if more tools adopt locking later.

## Environment

- `@kaeawc/auto-mobile` `0.0.45` (daemon + JUnit runner)
- Reproduced via `dev.jasonpearson.automobile.junit.AutoMobileRunner` executing a recorded YAML plan (`executePlan`)
- Confirmed not a stale-daemon issue - killed and let a fresh `0.0.45` daemon spawn via `bunx`, identical failure

**Comment by kaeawc** [comment]
Verified against current origin/main (623ea2e04a8c074b31ae06af2327fafef72d556a): PlanExecutor injects __lockNamespace only for tools that opt in via acceptsPlanLockNamespace; barrier and criticalSection are the only current opt-ins. The focused strict-schema regression suite passes (6 tests), and a fresh production build retains the guard in dist/src/index.js. This was already fixed by [9321c790](https://github.com/kaeawc/auto-mobile/commit/9321c790ae03fe1751c5f2e95078733302375be9). Closing as resolved on main; no new PR is needed.
